apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-prod

commonLabels:
  app.kubernetes.io/instance: guestbook-prod
  env: prod

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: guestbook
  - path: release-info-patch.yaml
    target:
      kind: Deployment
      name: guestbook

# Kargo rewrites `newTag` here on each promotion to prod.
images:
  - name: mirror.gcr.io/library/busybox
    newTag: "1.36"
