apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: guestbook:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: guestbook
  source:
    repoURL: https://github.com/wanghong230/guestbook-gitops.git
    targetRevision: stage/staging
    path: .
  destination:
    name: local-nonprod
    namespace: guestbook-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
